include: package:lint/analysis_options.yaml

linter: 
  rules:
    curly_braces_in_flow_control_structures: false

    unnecessary_new: false

    directives_ordering: false

    avoid_classes_with_only_static_members: false

    leading_newlines_in_multiline_strings: false

    sort_child_properties_last: false

    avoid_function_literals_in_foreach_calls: false

    sort_pub_dependencies: false